name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 1.0.1)'
        required: true
        type: string

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: npm ci

      - name: Install dependencies (Linux/Windows)
        if: matrix.os != 'macos-latest'
        run: npm ci --no-optional
        
      - name: Install system dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev

      - name: Build SQLite for Windows
        if: matrix.os == 'windows-latest'
        run: npm run rebuild

      - name: Generate macOS icon
        if: matrix.os == 'macos-latest'
        run: |
          chmod +x scripts/create-icns.sh
          ./scripts/create-icns.sh

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: true
          args: ${{ matrix.os == 'macos-latest' && '--mac --universal' || '' }}
